# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kxmlgui': '@stable'
    'frameworks/kwidgetsaddons': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kconfigwidgets': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kitemviews': '@stable'
    'frameworks/kiconthemes': '@stable'
    'frameworks/kcrash': '@stable'
    'frameworks/kdoctools': '@stable'

Options:
  require-passing-tests-on: [ '@all' ]
